name: Test

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      runOn: ${{ steps.setup.outputs.runOn }}
      slackChannel: ${{ steps.setup.outputs.slackChannel }}
      baseVersion: ${{ steps.getBaseVer.outputs.baseVersion }}
    steps: 
      - name: "Setup"
        id: setup
        shell: bash
        run: |
           # on Main branch
           if [ "${{ github.event_name }}" == "push" ] 
           then
              echo "::set-output runOn=main"
              echo "::set-output slackChannel=#jenkins-blink-ci-branch"
           elif [ "${{ github.event_name }} == "pull_request" ]
           then
              echo "::set-output runOn=pr"
              echo "::set-output slackChannel=#jenkins-blink-ci-branch"
           elif [ "${{ github.head_ref }} == *"release"* ]
           then
              echo "::set-output runOn=release"
              echo "::set-output slackChannel=#jenkins-blink-release"
           else
              echo "::set-output runOn=branch"
              echo "::set-output slackChannel=#jenkins-blink-ci-branch"
           fi
    
      - uses: actions/checkout@v3
          
      - name: "Get base version"
        id: getBaseVer
        shell: bash
        run: |
            baseVersion=`cat version.txt` 
            echo "::set-output baseVersion=${baseVersion}"
        
  calculateVersionName:
      uses: blinkops/github-actions-shared/.github/workflows/calcVersionNumber.yml@main
      needs: setup
      with:
          runsOn: ${{ needs.setup.jobs.setup.outputs.runOn }}
          baseVersion:  ${{ needs.setup.jobs.setup.outputs.baseVersion }}
         
  show:
    runs-on: ubuntu-latest
    needs: calculateVersionName
    steps:
      - run: echo ${{ needs.setup.jobs.calculateVersionName.outputs.versionName }}
    

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
